SET(CMAKE_CXX_STANDARD 20)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)

SET(IMGUI_SFML_FIND_SFML OFF)
SET(IMGUI_DIR "${CMAKE_CURRENT_SOURCE_DIR}/extern/imgui")
IF (DEFINED CMAKE_CXX_CLANG_TIDY)
    UNSET(CMAKE_CXX_CLANG_TIDY)
ENDIF()
ADD_SUBDIRECTORY(extern/imgui-sfml ${CMAKE_CURRENT_BINARY_DIR}/imgui-sfml)

FILE(GLOB_RECURSE
    ${PROJECT_NAME}_EDITOR_SOURCE_CODE
    CONFIGURE_DEPENDS
    "source/stay_editor/*.hpp"
    "source/stay_editor/*.cpp"
    "include/stay_editor/*.hpp"
)

ADD_LIBRARY(${PROJECT_NAME}_editor ${${PROJECT_NAME}_SOURCE_CODE})
TARGET_LINK_LIBRARIES(${PROJECT_NAME}_editor PUBLIC stay)
TARGET_LINK_LIBRARIES(${PROJECT_NAME}_editor PRIVATE ImGui-SFML::ImGui-SFML)
TARGET_INCLUDE_DIRECTORIES(${PROJECT_NAME}_editor PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/extern/imgui)
TARGET_INCLUDE_DIRECTORIES(${PROJECT_NAME}_editor PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include/stay_editor)